import type { Meta, StoryObj } from "@storybook/react";
import MainMenu from "./MainMenu";
import Image from "next/image";

const meta: Meta<typeof MainMenu> = {
  component: MainMenu,
  argTypes: {
    homepageUrl: {
      control: "text",
      description: "Where to take the user once they click the logo.",
    },
    logo: {
      control: "object",
      description: "The logo. It can be a React component...",
    },
    menuItems: {
      control: "object",
      description: "The menu array.",
    },
  },
};

export default meta;

type Story = StoryObj<typeof MainMenu>;

const BlackBullLogo = () => {
  return (
    <Image src="/logo/c.png" width="197" height="47" alt="BlackBull Academy" />
  );
};

const menuItems = [
  {
    ID: 190,
    post_author: "1",
    post_date: "2024-10-09 18:42:13",
    post_date_gmt: "2024-10-09 18:42:13",
    post_content: " ",
    post_title: "",
    post_excerpt: "",
    post_status: "publish",
    comment_status: "closed",
    ping_status: "closed",
    post_password: "",
    post_name: "190",
    to_ping: "",
    pinged: "",
    post_modified: "2024-10-09 18:42:13",
    post_modified_gmt: "2024-10-09 18:42:13",
    post_content_filtered: "",
    post_parent: 0,
    guid: "http://academydata.blackbull.local/2024/10/09/190/",
    menu_order: 1,
    post_type: "nav_menu_item",
    post_mime_type: "",
    comment_count: "0",
    filter: "raw",
    db_id: 190,
    menu_item_parent: "0",
    object_id: "2",
    object: "lesson_taxonomy",
    type: "taxonomy",
    type_label: "Lessons Categories",
    url: "http://academydata.blackbull.local/lesson_taxonomy/forex/",
    title: "Forex",
    target: "",
    attr_title: "",
    description: "",
    classes: [""],
    xfn: "",
    childItems: [
      {
        ID: 192,
        post_author: "1",
        post_date: "2024-10-09 18:59:28",
        post_date_gmt: "2024-10-09 18:59:28",
        post_content: " ",
        post_title: "",
        post_excerpt: "",
        post_status: "publish",
        comment_status: "closed",
        ping_status: "closed",
        post_password: "",
        post_name: "192",
        to_ping: "",
        pinged: "",
        post_modified: "2024-10-09 18:59:28",
        post_modified_gmt: "2024-10-09 18:59:28",
        post_content_filtered: "",
        post_parent: 2,
        guid: "http://academydata.blackbull.local/2024/10/09/192/",
        menu_order: 2,
        post_type: "nav_menu_item",
        post_mime_type: "",
        comment_count: "0",
        filter: "raw",
        db_id: 192,
        menu_item_parent: "190",
        object_id: "3",
        object: "lesson_taxonomy",
        type: "taxonomy",
        type_label: "Lessons Categories",
        url: "http://academydata.blackbull.local/lesson_taxonomy/beginner-forex-tutorial/",
        title: "Beginner Forex Tutorial",
        target: "",
        attr_title: "",
        description: "",
        classes: [""],
        xfn: "",
      },
      {
        ID: 193,
        post_author: "1",
        post_date: "2024-10-09 18:59:28",
        post_date_gmt: "2024-10-09 18:59:28",
        post_content: " ",
        post_title: "",
        post_excerpt: "",
        post_status: "publish",
        comment_status: "closed",
        ping_status: "closed",
        post_password: "",
        post_name: "193",
        to_ping: "",
        pinged: "",
        post_modified: "2024-10-09 18:59:28",
        post_modified_gmt: "2024-10-09 18:59:28",
        post_content_filtered: "",
        post_parent: 2,
        guid: "http://academydata.blackbull.local/2024/10/09/193/",
        menu_order: 3,
        post_type: "nav_menu_item",
        post_mime_type: "",
        comment_count: "0",
        filter: "raw",
        db_id: 193,
        menu_item_parent: "190",
        object_id: "4",
        object: "lesson_taxonomy",
        type: "taxonomy",
        type_label: "Lessons Categories",
        url: "http://academydata.blackbull.local/lesson_taxonomy/intermediate-forex-tutorial/",
        title: "Intermediate Forex Tutorial",
        target: "",
        attr_title: "",
        description: "",
        classes: [""],
        xfn: "",
      },
      {
        ID: 194,
        post_author: "1",
        post_date: "2024-10-09 18:59:28",
        post_date_gmt: "2024-10-09 18:59:28",
        post_content: " ",
        post_title: "",
        post_excerpt: "",
        post_status: "publish",
        comment_status: "closed",
        ping_status: "closed",
        post_password: "",
        post_name: "194",
        to_ping: "",
        pinged: "",
        post_modified: "2024-10-09 18:59:28",
        post_modified_gmt: "2024-10-09 18:59:28",
        post_content_filtered: "",
        post_parent: 2,
        guid: "http://academydata.blackbull.local/2024/10/09/194/",
        menu_order: 4,
        post_type: "nav_menu_item",
        post_mime_type: "",
        comment_count: "0",
        filter: "raw",
        db_id: 194,
        menu_item_parent: "190",
        object_id: "5",
        object: "lesson_taxonomy",
        type: "taxonomy",
        type_label: "Lessons Categories",
        url: "http://academydata.blackbull.local/lesson_taxonomy/advanced-forex-tutorial/",
        title: "Advanced Forex Tutorial",
        target: "",
        attr_title: "",
        description: "",
        classes: [""],
        xfn: "",
      },
    ],
  },
];

export const Common: Story = {
  args: {
    homepageUrl: "http://blackbull.com",
    logo: <BlackBullLogo />,
    menuItems: menuItems,
  },
};
